name: update-version
description: Update the version in pyproject.toml

inputs:
  version:
    description: The new version number
    required: true

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install tomli-w
      run: pip install tomli-w
      shell: bash

    - name: Update version
      run: python update-version.py ${{ inputs.version }}
      shell: bash
