name: CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md

jobs: 
  build-wheels:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_BUILD: cp312-*
          CIBW_ARCHS_MACOS: "x86_64 aarch64"
          CIBW_ARCHS_LINUX: "x86_64 arm64"
          CIBW_ARCHS_WINDOWS: "AMD64"
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  publish:
    name: Publish wheels to pypi
    runs-on: ubuntu-latest
    needs: build-wheels
    steps:
      - name: Download all dists
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          verbose: true