name: CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  build:
    name: Build and install the package
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Pull pybind11
        run: git submodule update --init --recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install setuptools
        run: pip install wheel setuptools
      - name: Build the package distributions
        run: python setup.py sdist bdist_wheel
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist
  
  publish:
    name: Publish to pypi
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Show dist
        run: ls dist
