name: CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  build:
    name: Build and install the package
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Pull pybind11
        run: git submodule update --init --recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install setuptools
        run: pip install setuptools
      - name: Build the package distributions
        run: python setup.py sdist bdist_wheel
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}     
          repository-url: https://test.pypi.org/legacy/ 