name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  build-linux:
    name: Build wheel on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0
        env:
          CIBW_PLATFORM: linux
          CIBW_ARCHS: x86_64
          CIBW_BUILD: cp312-*,cp313-*

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ runner.os }}-${{ runner.arch }}
          path: wheelhouse/*.whl

  build-windows:
    name: Build wheel on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps
        with:
          build-type: Release

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0
        env:
          CIBW_PLATFORM: windows
          CIBW_ARCHS: AMD64
          CIBW_BUILD: cp312-*,cp313-*

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ runner.os }}-${{ runner.arch }}
          path: wheelhouse/*.whl

  build-macos:
    name: Build wheel on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps
        with:
          build-type: Release

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0
        env:
          CIBW_PLATFORM: macos
          CIBW_ARCHS: arm64
          CIBW_BUILD: cp312-*,cp313-*

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ runner.os }}-${{ runner.arch }}
          path: wheelhouse/*.whl
