name: CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  build:
    name: Build and install the package
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Pull pybind11
        run: git submodule update --init --recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install package
        run: pip install ./
      - name: Test package import
        run: python -c "from phreeqc import Phreeqc;p = Phreeqc()"