name: Build wheels and publish to test pypi

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: "Version of phreeqc package"
        type: string
        required: true

jobs:
  build-sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Update version
        run: python script.py version ${{ github.event.inputs.package_version }}
      - name: Build sdist
        run: pipx run build --sdist
      - name: Check metadata
        run: pipx run twine check dist/*
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  build-wheels:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-13]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/checkout@v4
        with:
          repository: Maryam1124/iphreeqc
          token: ${{ secrets.EXPERIMENT_REPO_PAT }}
          path: iphreeqc
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Update version
        run: python script.py version ${{ github.event.inputs.package_version }}
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_BUILD: cp311-*
          CIBW_ARCHS_MACOS: x86_64
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_BUILD: cp39-*
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_ARCHS_MACOS: x86_64
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  publish:
    name: Publish wheels to pypi
    runs-on: ubuntu-latest
    needs: [build-wheels, build-sdist]
    permissions:
      id-token: write
      attestations: write
    steps:
      - name: Download all dists
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: cibw-*
          merge-multiple: true
      - name: Generate artifact attestation for sdist and wheels
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "dist/*"
      - name: Publish package to test pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          verbose: true
          attestations: true
          repository-url: https://test.pypi.org/legacy/
